### PR TITLE
Cope with absence of __p___argc, __p___argv, __p___wargv in 64-bit msvcrt.dll

### PR DESCRIPTION
**Pull request by datadiode**
The proposed change happened to help me out with a 64-bit build.
I cannot tell if there are msvcrt dlls around which in turn lack the exports which I'm relying on, so please judge carefully.

### CODE REVIEW

**Comment by kinke** [comment]
What did it help you out with? Do you use some CRT functionality that requires the MSVCRT vars to be set, instead of the 'private' ones here?

**Comment by datadiode** [comment]
The ReleaseL 64-bit build configuration of https://github.com/datadiode/PatchPE failed at linking, due to the 'private' variables being unresolvable.

**Comment by kinke** [comment]
When using which MSVCRT?

**Comment by kinke** [comment]
I'm asking because linking an executable works just fine with D/LDC, using the generated `vcruntime140.lib`.

**Comment by datadiode** [comment]
I was linking with msvcrt.lib. vcruntime140.lib creates dependencies which I intend to avoid.

**Comment by kinke** [comment]
Okay that explains it, so some ancient pre-UCRT only features these symbols as exports.

**Comment by datadiode** [comment]
Closing due to lack of confidence that this is actually a sane approach.

**Comment by kinke** [comment]
You might have more luck with `msvcrt120.lib`, for the Visual C++ 2013 runtime, the last one before UCRT, which you probably want to avoid. My only interest wrt. LDC is vcruntime140.lib, for Visual C++ 2015 and the UCRT with its much improved C99 support. That's e.g. why there are `msvcrt140.aliases*` files only. The other versions are unused & untested.

**Pull request closed without merging**
